Added myself
thedropbears/git-training pull request #4
Opened 2021-11-13 00:13 UTC by deltaqyto

2021-11-13 03:13 UTC, auscompgeek requested changes
lbtm

2021-11-13 03:13 UTC, auscompgeek commented on names/deltaqyto.txt
> +delta
*gasp*
the delta?

2021-11-14 00:32 UTC, deltaqyto commented on names/deltaqyto.txt
> +delta
It would appear so

2024-12-08 02:39 UTC, auscompgeek approved these changes
you know what good enough

2024-12-08 02:39 UTC, merged